USE PREMIERECO


---LAB 1

SELECT 'EMPLOYEE', COUNT(*) FROM EMPLOYEE UNION ALL
SELECT 'SALESREP', COUNT(*) FROM SALESREP UNION ALL
SELECT 'PART', COUNT(*) FROM PART UNION ALL
SELECT 'CUSTOMER', COUNT(*) FROM CUSTOMER UNION ALL
SELECT 'ORDERS', COUNT(*) FROM ORDERS UNION ALL
SELECT 'ORDER_LINE', COUNT(*) FROM ORDER_LINE

-- LAB 2
SELECT * FROM CUSTOMER

-- LAB 3
SELECT *
FROM PART
-- WHERE 
-- GROUP BY 
-- HAVING 
-- ORDER BY 

-- LAB 4
SELECT CUST_NUM, CUST_NAME, CUST_STATE
FROM CUSTOMER

-- LAB 5
SELECT PART_NUM, PART_DESCRIPTION, PRICE
FROM PART

-- LAB 6
SELECT DISTINCT CUST_CITY
FROM CUSTOMER

-- LAB 7
SELECT CUST_NAME, CUST_CITY + ','+ CUST_STATE AS FullLocation
FROM CUSTOMER

-- LAB 8
SELECT PART_NUM, PART_DESCRIPTION, UNITS_ON_HAND * PRICE AS InventoryValue
FROM PART

-- LAB 9
SELECT FNAME, LNAME,
DATEDIFF (year, HIRE_DATE, GETDATE()) AS YearsOfService
FROM EMPLOYEE

-- LAB 10
SELECT PART_DESCRIPTION,
CASE CATEGORY
WHEN 'AP' THEN 'Appliance'
WHEN 'HW' THEN 'Housewares'
WHEN 'SG' THEN 'Sporting Goods'
ELSE 'Other'
END AS CategoryName
FROM PART